backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        $this->layout ='loginLayout';
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
   
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    public function beforeAction($action) 
    { 
    $this->enableCsrfValidation = false; 
    return parent::beforeAction($action); 
    }
    /**
     * {@inheritdoc}
     */
    public static function allowedDomains() {
        return [
             '*',                        // star allows all domains
            'http://localhost',
            'http://test2.example.com',
        ];
    }
    
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],

            'corsFilter'  => [
                'class' => \yii\filters\Cors::className(),
                'cors'  => [
                    // restrict access to domains:
                    'Origin'                           => static::allowedDomains(),
                    'Access-Control-Request-Method'    => ['POST'],
                    'Access-Control-Allow-Credentials' => true,
                    'Access-Control-Max-Age'           => 3600,                 // Cache (seconds)
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render('index');
       
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        $this->layout ='loginLayout';
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionUser()
    {
        $session = Yii::$app->session;
        $user_id = $session->get('user_id');
        
        if($user_id==null){
            return $this->render('index'); 
        }
        else{
        $this->layout ='userLayout';
        return $this->render('user');
    }
}

    public function actionBooking()
    {
        $session = Yii::$app->session;
        $user_id = $session->get('user_id');
        
        if($user_id==null){
            return $this->render('index'); 
        }
        else{
        $this->layout ='bookingLayout';
        return $this->render('booking');
    }
}
    public function actionReview()
    {
        $session = Yii::$app->session;
        $user_id = $session->get('user_id');
        
        if($user_id==null){
            return $this->render('index'); 
        }
        else{
            $this->layout ='reviewLayout';
        return $this->render('review');
        }
    }
    public function actionSubmitreview()
    {
        $session = Yii::$app->session;
        $user_id = $session->get('user_id');
        
        if($user_id==null){
            return $this->render('index'); 
        }
        else{
        $this->layout='subreviewLayout';
        return $this->render('subreview');
    }
    }
    public function actionSample()
    {
        $this->layout='sample';
        return $this->render('sampleview');
    }
    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
}

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>This is the About page. You may modify the following file to customize its content:</p>

    <code><?= __FILE__ ?></code>
</div>

frontend/views/site/booking.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Bookings';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-booking">
<div id="all">
      <div id="content">
        <div class="container" style="padding-top:50px">
          <div class="row">
            <div class="col-lg-12">
              <!-- breadcrumb-->
              <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><?= Html::a('Home', ['/site/index'],['style' => 'color:#555555;text-decoration:none']) ?></li>
                  <li aria-current="page" class="breadcrumb-item active">My Bookings</li>
                </ol>
              </nav>
            </div>
            <div class="col-lg-3">
              <!--
              *** CUSTOMER MENU ***
              _________________________________________________________
              -->
              <div class="card sidebar-menu" >
                <div class="card-header">
                  <h3 class="h4 card-title">Customer section</h3>
                </div>
                <div class="card-body" style="padding:10px">
                <span style="display:flex;padding-left:20px"><i class="fa fa-list" style="padding-top:4px;padding-right:9px;color:#555555;"></i><?= Html::a('My Account', ['/site/user'],['style' => 'color:#555555;text-decoration:none']) ?></span>
                  <span style="display:flex;padding-left:20px;margin-top:20px;background-color:#186bbd"  class="nav-link active"><i class="fa fa-heart" style="padding-top:4px;padding-right:9px;color:white;"></i><?= Html::a('My Bookings', ['/site/booking'],['style' => 'color:white;text-decoration:none']) ?></span>
                  <span style="display:flex;padding-left:20px;padding-top:20px"><i class="fa fa-user" style="padding-top:4px;padding-right:9px;color:#555555;"></i><?= Html::a('View Reviews', ['/site/review'],['style' => 'color:#555555;text-decoration:none']) ?></span>
                  <span style="display:flex;padding-left:20px;padding-top:20px"><i class="fa fa-edit" style="padding-top:4px;padding-right:9px;color:#555555;"></i><?= Html::a('Submit Review', ['/site/submitreview'],['style' => 'color:#555555;;text-decoration:none']) ?></span>
                
                </div>
              </div>
              <!-- /.col-lg-3-->
              <!-- *** CUSTOMER MENU END ***-->
            </div>
            <div id="customer-orders" class="col-lg-9">
              <div class="box">
                <h1>My Bookings</h1>
                <p class="lead">Your Bookings on one place.</p>
                
                <hr>
                <div class="table-responsive">
                  <table class="table table-hover">
                    <thead>
                      <tr>
                        <th>Booking ID</th>
                        <th>Number Of Persons</th>
                        <th>Total Amount</th>
                        <th>Date of Booking</th>
                        <th>Date Of Ride</th>
                      </tr>
                    </thead>
                    <tbody id='table'>
                      <!--<tr>
                        <th># 1735</th>
                        <td>22/06/2013</td>
                        <td>$ 150.00</td>
                        <td><span class="badge badge-info">Being prepared</span></td>
                        <td><a href="customer-order.html" class="btn btn-primary btn-sm">View</a></td>
                      </tr>-->
                     
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

   
</div>

frontend/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'subject') ?>

                <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>

</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">

   <center> <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p></center>

    <div class="row">
    <div class="col-lg-4"></div>
        <div class="col-lg-4">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <?= $form->field($model, 'rememberMe')->checkbox() ?>

                <div style="color:#999;margin:1em 0">
                    If you forgot your password you can <?= Html::a('reset it', ['site/request-password-reset']) ?>.
                </div>

                <div class="form-group">
                 <center>   <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?></center>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/profile.php
<?php

/* @var $this yii\web\View */

$this->title = 'profile';
?>
<div class="site-index">
<div class="menu trans_700">
		<div class="menu_content d-flex flex-column align-items-center justify-content-center text-center">
			<div class="menu_close_container"><div class="menu_close"></div></div>
			<img src="images/smallboat.png" alt="">
			<ul>
				<li class="menu_item"><a href="#">home</a></li>
				<!--<li class="menu_item"><a href="about.html">about us</a></li>-->
				<li class="menu_item"><a href="offers.html">Book Now</a></li>
				<!--<li class="menu_item"><a href="blog.html">news</a></li>-->
				<li class="menu_item"><a href="contact.html">contact</a></li>
			</ul>
		</div>
	</div>
  <div class="home" style="height:600px">
  <div id="myCarousel" class="carousel slide" data-ride="carousel" style="padding-top:10px">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <img src="images/banner1.png" alt="Los Angeles" style="width:100%;height:680px">
    </div>

    <div class="item">
      <img src="images/banner2.png" alt="Chicago" style="width:100%;height:680px">
    </div>

    <div class="item">
      <img src="images/banner3.png" alt="New York" style="width:100%;height:680px">
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</div>


	

frontend/views/site/review.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Bookings';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-review">
<div id="all">
      <div id="content">
        <div class="container" style="padding-top:50px">
          <div class="row">
            <div class="col-lg-12">
              <!-- breadcrumb-->
              <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><?= Html::a('Home', ['/site/index'],['style' => 'color:#555555;text-decoration:none']) ?></li>
                  <li aria-current="page" class="breadcrumb-item active">Reviews</li>
                </ol>
              </nav>
            </div>
            <div class="col-lg-3">
              <!--
              *** CUSTOMER MENU ***
              _________________________________________________________
              -->
              <div class="card sidebar-menu" >
                <div class="card-header">
                  <h3 class="h4 card-title">Customer section</h3>
                </div>
                <div class="card-body" style="padding:10px">
                  <ul class="nav nav-pills flex-column" >
                  <span style="display:flex;padding-left:20px"><i class="fa fa-list" style="padding-top:4px;padding-right:9px;color:#555555;"></i><?= Html::a('My Account', ['/site/user'],['style' => 'color:#555555;text-decoration:none']) ?></span>
                  <span style="display:flex;padding-left:20px;padding-top:20px"><i class="fa fa-heart" style="padding-top:4px;padding-right:9px;color:#555555;"></i><?= Html::a('My Bookings', ['/site/booking'],['style' => 'color:#555555;text-decoration:none']) ?></span>
                  <span style="display:flex;padding-left:20px;margin-top:20px;background-color:#186bbd" class="nav-link active"><i class="fa fa-user" style="padding-top:4px;padding-right:9px;color:white;"></i><?= Html::a('View Reviews', ['/site/review'],['style' => 'color:white;text-decoration:none']) ?></span>
                  <span style="display:flex;padding-left:20px;padding-top:20px"><i class="fa fa-edit" style="padding-top:4px;padding-right:9px;color:#555555;"></i><?= Html::a('Submit Review', ['/site/submitreview'],['style' => 'color:#555555;;text-decoration:none']) ?></span>
                  
                </div>
              </div>
              <!-- /.col-lg-3-->
              <!-- *** CUSTOMER MENU END ***-->
            </div>
            <div id="customer-orders" class="col-lg-9">
              <div class="box">
                <h1>View Reviews</h1>
              
                
                
                <div id="id">
               <!--<span style="color:#555555;font-weight:bold;display:flex" id="username">User Name <label style="padding-left:450px">Ratings star</label></span>
               <p style="color:#555555;font-weight:bold">Date</p>
               <P style="color:#555555;font-weight:bold">Review Details</p>-->
               </div>
                
               <hr>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

   
</div>

frontend/views/site/sampleview.php
<?php

/* @var $this yii\web\View */

$this->title = 'My Yii Application';
?>
<div class="site-sampleview">


</div>

frontend/views/site/subreview.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Submit Review';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-submitreview">
<div id="all">
      <div id="content">
        <div class="container" style="padding-top:50px">
          <div class="row">
            <div class="col-lg-12">
              <!-- breadcrumb-->
              <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><?= Html::a('Home', ['/site/index'],['style' => 'color:#555555;text-decoration:none']) ?></li>
                  <li aria-current="page" class="breadcrumb-item active">Submit Reviews</li>
                </ol>
              </nav>
            </div>
            <div class="col-lg-3">
              <!--
              *** CUSTOMER MENU ***
              _________________________________________________________
              -->
              <div class="card sidebar-menu" >
                <div class="card-header">
                  <h3 class="h4 card-title">Customer section</h3>
                </div>
                <div class="card-body" style="padding:10px">
                 
                  <span style="display:flex;padding-left:20px"><i class="fa fa-list" style="padding-top:4px;padding-right:9px;color:#555555;"></i><?= Html::a('My Account', ['/site/user'],['style' => 'color:#555555;text-decoration:none']) ?></span>
                  <span style="display:flex;padding-left:20px;padding-top:20px"><i class="fa fa-heart" style="padding-top:4px;padding-right:9px;color:#555555;"></i><?= Html::a('My Bookings', ['/site/booking'],['style' => 'color:#555555;text-decoration:none']) ?></span>
                  <span style="display:flex;padding-left:20px;padding-top:20px"><i class="fa fa-user" style="padding-top:4px;padding-right:9px;color:#555555;"></i><?= Html::a('View Reviews', ['/site/review'],['style' => 'color:#555555;text-decoration:none']) ?></span>
                  <span style="display:flex;padding-left:20px;margin-top:20px;background-color:#186bbd" class="nav-link active"><i class="fa fa-edit" style="padding-top:4px;padding-right:9px;color:white;"></i><?= Html::a('Submit Review', ['/site/submitreview'],['style' => 'color:white;text-decoration:none']) ?></span>
                
                  
                </div>
              </div>
              <!-- /.col-lg-3-->
              <!-- *** CUSTOMER MENU END ***-->
            </div>
            <div id="customer-orders" class="col-lg-9">
              <div class="box">
                <h1>Submit a review</h1>
                <hr>
                <form>
                  
                    <div class="col-md-6">
                      <div class="form-group">
                        <label for="firstname">Your Rating</label>
                        <input id="firstname" type="text" class="form-control" name="rating">
                      </div>
                    </div>
  
                    <div class="col-md-12">
                      <div class="form-group">
                        <label for="street">Your Experience</label>
                        <textarea id="street" rows=4 class="form-control" name="remark"></textarea>
                      </div>
                    </div>
                  
                  <!-- /.row-->
                  
                    <div class="col-md-12 text-center">
                      <button type="button" class="btn" style="background-color:#0295ad;color:white" onClick="submitreview()"><i class="fa fa-save"></i> Submit Review</button>
                    </div>
					 </form>
           </div>
                
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

   
</div>

frontend/views/site/user.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'User';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-user">
<div id="all">
      <div id="content">
        <div class="container" style="padding-top:50px">
          <div class="row">
            <div class="col-lg-12">
              <!-- breadcrumb-->
              <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><?= Html::a('Home', ['/site/index'],['style' => 'color:#555555;text-decoration:none']) ?></li>
                  <li aria-current="page" class="breadcrumb-item active">My account</li>
                </ol>
              </nav>
            </div>
            <div class="col-lg-3">
              <!--
              *** CUSTOMER MENU ***
              _________________________________________________________
              -->
              <div class="card sidebar-menu" >
                <div class="card-header">
                  <h3 class="h4 card-title">Customer section</h3>
                </div>
                <div class="card-body" style="padding:10px">
                <span style="display:flex;padding-left:20px;background-color:#186bbd" class="nav-link active"><i class="fa fa-list" style="padding-top:4px;padding-right:9px;color:white;"></i><?= Html::a('My Account', ['/site/user'],['style' => 'color:white;text-decoration:none']) ?></span>
                  <span style="display:flex;padding-left:20px;padding-top:20px"><i class="fa fa-heart" style="padding-top:4px;padding-right:9px;color:#555555;"></i><?= Html::a('My Bookings', ['/site/booking'],['style' => 'color:#555555;text-decoration:none']) ?></span>
                  <span style="display:flex;padding-left:20px;margin-top:20px;"><i class="fa fa-user" style="padding-top:4px;padding-right:9px;color:#555555;"></i><?= Html::a('View Reviews', ['/site/review'],['style' => 'color:#555555;text-decoration:none']) ?></span>
                  <span style="display:flex;padding-left:20px;padding-top:20px"><i class="fa fa-edit" style="padding-top:4px;padding-right:9px;color:#555555;"></i><?= Html::a('Submit Review', ['/site/submitreview'],['style' => 'color:#555555;;text-decoration:none']) ?></span>
                  
                </div>
              </div>
              <!-- /.col-lg-3-->
              <!-- *** CUSTOMER MENU END ***-->
            </div>
            <div class="col-lg-9">
              <div class="box">
              <h1>My account</h1>
                <h3 class="mt-2">Personal details</h3>
                <form>
                  <div class="row">
                    <div class="col-md-6">
                      <div class="form-group">
                        <label for="firstname">Username</label>
                        <input id="firstname" type="text" class="form-control" name="name">
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group">
                        <label for="company">EmailID</label>
                        <input id="company" type="text" class="form-control" name="email">
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group">
                        <label for="street">Contact Number</label>
                        <input id="street" type="text" class="form-control" name="contact">
                      </div>
                    </div>
                  </div>
                  <!-- /.row-->
                  
                    <div class="col-md-12 text-center">
                      <button type="button" class="btn" style="background-color:#0295ad;color:white" onClick="updateprofile()"><i class="fa fa-save"></i> Save changes</button>
                    </div>
					 </form>
					
                <h3 class="mt-5">Change password</h3>
                <form>
                  <div class="row">
                    <div class="col-md-6">
                      <div class="form-group">
                        <label for="password_old">Old password</label>
                        <input id="password_old" type="password" class="form-control">
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-6">
                      <div class="form-group">
                        <label for="password_1">New password</label>
                        <input id="password_1" type="password" class="form-control" name="password">
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group">
                        <label for="password_2">Retype new password</label>
                        <input id="password_2" type="password" class="form-control" name="password1">
                      </div>
                    </div>
                  </div>
                  <!-- /.row-->
                  <div class="col-md-12 text-center">
                    <button type="button" class="btn" style="background-color:#0295ad;color:white" onClick="changepassword()"><i class="fa fa-save" ></i> Save new password</button>
                  </div>
                </form>
                  
               
				</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

   
</div>